GET http://localhost:3000/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3ODg0ODM0NiwiZXhwIjoxNzc4ODUxOTQ2fQ.fmaU7HDVshg7KwvsJxuEhvQCuLX6khiJ5jkcsIxT7I4