GET http://localhost:3000/cardapio/22222222-2222-2222-2222-222222222222
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3ODg1Mjg2MiwiZXhwIjoxNzc4ODU2NDYyfQ.Il0GMgSbg2emateoqxqFpDOww2iCSVVPM1SR6EeN-8k