GET http://localhost:3000/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3OTM2NjU1MCwiZXhwIjoxNzc5MzcwMTUwfQ.WBs8tAsrEirxUXCuZNKPB35ZbRlTIXCFr3kbO3UUhz8