GET http://localhost:3000/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc4NjgxMzY3LCJleHAiOjE3Nzg2ODQ5Njd9.rxuq7SA99Sla8CzuOlyknAQZSTjSJOehfSm4aLJu4Vc