GET http://localhost:3000/pagamentos/f0000000-0000-0000-0000-000000000001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3OTM3NTk2MywiZXhwIjoxNzc5Mzc5NTYzfQ.yDqpgrc5NEGthcXBI5ogrDJarTMnnXv-5EVvxLOX7TY