@unidade_id = 22222222-2222-2222-2222-222222222222

POST http://localhost:3000/pedido
Content-Type: application/json

{
    "unidade_id": "{{unidade_id}}",
    "items": [
        {
            "produto_id": "cccccccc-0000-0000-0000-000000000001",
            "quantidade": 2
        },
        {
            "produto_id": "cccccccc-0000-0000-0000-000000000002",
            "quantidade": 4
        }
    ],
    "canal_pedido": "app",
    "forma_pagamento": "dinheiro"
}