# @name register_user
POST http://localhost:3000/register
Content-Type: application/json

{
    "unidade_id": "22222222-2222-2222-2222-222222222222",
    "name": "Cliente Teste",
    "email": "cliente@teste.com",
    "password": "senha123",
    "ativo_programa_fidelidade": true
}

###

# @name login_user
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "cliente@teste.com",
    "password": "senha123"
}

###

# @name get_login
@meu_token = {{login_user.response.body.token}}

GET http://localhost:3000/login
Authorization: Bearer {{meu_token}}